#/bin/bash
rm -r $LLVM_HOME/project/release $LLVM_HOME/install
mkdir $LLVOM_HOME/release $LLVOM_HOME/install
cd $LLVOM_HOME/release
#cmake -G Ninja -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=../install -DLLVM_TARGETS_TO_BUILD='X86' -DLLVM_ENABLE_PROJECTS="lldb;clang;clang-tools-extra" -DLLVM_USE_LINKER=gold -DLLVM_USE_SPLIT_DWARF=ON -DBUILD_SHARED_LIBS=ON ../llvm
cmake -G Ninja -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=../install -DLLVM_TARGETS_TO_BUILD='X86' -DLLVM_ENABLE_PROJECTS="lldb;clang" -DLLVM_USE_LINKER=gold -DLLVM_USE_SPLIT_DWARF=ON -DBUILD_SHARED_LIBS=ON $LLVM_HOME/llvm
